import path from "node:path";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
	plugins: [react()],
	resolve: {
		alias: {
			"@": path.resolve(__dirname, "./src"),
		},
	},
	test: {
		environment: "happy-dom",
		env: {
			NEXT_PUBLIC_TEMPO_CHAIN_ID: "42431",
			NEXT_PUBLIC_TEMPO_RPC_HTTP: "https://rpc.moderato.tempo.xyz",
			NEXT_PUBLIC_TEMPO_RPC_WS: "wss://rpc.moderato.tempo.xyz",
			NEXT_PUBLIC_TEMPO_SPONSOR_URL: "https://sponsor.moderato.tempo.xyz",
			NEXT_PUBLIC_TEMPO_EXPLORER_URL: "https://explore.tempo.xyz",
			NEXT_PUBLIC_TOKENS:
				'[{"name":"AlphaUSD","symbol":"AUSD","decimals":6,"address":"0x20c0000000000000000000000000000000000001"},{"name":"BetaUSD","symbol":"BUSD","decimals":6,"address":"0x20c0000000000000000000000000000000000002"}]',
			NEXT_PUBLIC_DEFAULT_TOKEN: "AlphaUSD",
			NEXT_PUBLIC_APP_ENV: "development",
		},
		include: ["src/**/*.test.{ts,tsx}"],
		setupFiles: ["./src/test/setup.ts"],
		coverage: {
			provider: "v8",
			include: ["src/**/*.{ts,tsx}"],
			exclude: [
				"src/test/**",
				"src/**/*.test.{ts,tsx}",
				"src/app/layout.tsx",
				"src/app/globals.css",
				"src/sw.ts",
				"src/app/**/page.tsx",
				"src/app/api/**",
				"src/db/index.ts",
				"src/components/providers.tsx",
				"src/lib/idb-persister.ts",
				"src/lib/session.ts",
				"src/domain/auth/actions/**",
				"src/domain/accounts/actions/**",
				"src/domain/treasury/actions/**",
				"src/domain/swap/actions/**",
				"src/domain/multisig/actions/**",
				"src/domain/payments/actions/**",
				"src/domain/auth/queries/**",
				"src/domain/accounts/queries/**",
				"src/domain/treasury/queries/**",
				"src/domain/swap/queries/**",
				"src/domain/multisig/queries/**",
				"src/domain/payments/queries/**",
				"src/domain/**/hooks/**",
				"src/lib/tempo/types.ts",
				"src/lib/tempo/client.ts",
				"src/app/**/dashboard-content.tsx",
				"src/app/**/dashboard-recent-transactions.tsx",
				"src/app/**/transactions-content.tsx",
				"src/app/**/transaction-detail-content.tsx",
				"src/app/**/settings-content.tsx",
				"src/app/**/accounts-content.tsx",
				"src/app/**/account-detail-content.tsx",
				"src/app/**/swap-content.tsx",
				"src/app/create/page.tsx",
				"src/app/global-error.tsx",
				"src/sentry-*.ts",
				"src/instrumentation.ts",
			],
			thresholds: {
				lines: 90,
				functions: 90,
				branches: 90,
				statements: 90,
			},
		},
	},
});
